{% set name = "pysteps" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7079a6d383822b3ae4f446250ad1c222e5a1f693636ec35281ef503770cea413

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - numpy 1.16.*
    - cython
    - pip
    - openmp 4.0.*  # [osx]
    - jsmin
    - scipy
    - matplotlib-base
    - jsonschema
  run:
    - python
    - openmp 4.0.*  # [osx]
    - jsmin
    - jsonschema
    - matplotlib-base
    - netCDF4
    - {{ pin_compatible('numpy') }}
    - opencv
    - pillow
    - pyproj
    - scipy

test:
  imports:
    - pysteps

about:
  home: https://pysteps.github.io/
  license: BSD-3-Clause
  license_family: BSD
  summary: Python framework for short-term ensemble prediction systems
  license_file: LICENSE
  description: |
    pySTEPS is a community-driven initiative for developing and maintaining an
    easy to use, modular, free and open-source Python framework for short-term
    ensemble prediction systems.
  doc_url: https://pysteps.readthedocs.io/
  dev_url: https://github.com/pySTEPS/pysteps

extra:
  recipe-maintainers:
    - aperezhortal
    - pulkkins
    - dnerini
