{% set name = "pysteps" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12c59367b04e4ab361347d860c8fbd2db03ebccb3958f2130d8243a5cb0a85fb

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - numpy >=1.17
    - cython
    - pip
    - openmp  # [osx]
  run:
    - python
    - openmp  # [osx]
    - jsmin
    - jsonschema
    - matplotlib
    - netCDF4
    - {{ pin_compatible('numpy') }}
    - opencv
    - pillow
    - pyproj
    - scipy

test:
  imports:
    - pysteps

about:
  home: https://pysteps.github.io/
  license: BSD-3-Clause
  license_family: BSD
  summary: Python framework for short-term ensemble prediction systems
  license_file: LICENSE
  description: |
    pySTEPS is a community-driven initiative for developing and maintaining an
    easy to use, modular, free and open-source Python framework for short-term
    ensemble prediction systems.
  doc_url: https://pysteps.readthedocs.io/
  dev_url: https://github.com/pySTEPS/pysteps

extra:
  recipe-maintainers:
    - aperezhortal
    - pulkkins
    - dnerini
