{% set name = "pysteps" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/a1/22/ddc583bbae5b4cdd34c7cb2e30e96f88df4ad9197065502ad4e330d8e4b1/pysteps-{{ version }}.tar.gz
  sha256: a3dbd72a6fe368b42d7761efe4a3b658b12224ec51e2cf7276641d2fc43cf20d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<310 or py>312]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - setuptools
  host:
    - python
    - numpy >=1.17
    - cython
    - pip
    - setuptools
    - openmp  # [osx]
  run:
    - python
    - openmp  # [osx]
    - jsmin
    - jsonschema
    - matplotlib
    - netCDF4
    - opencv
    - pillow
    - pyproj
    - scipy

test:
  imports:
    - pysteps

about:
  home: https://pysteps.github.io/
  license: BSD-3-Clause
  license_family: BSD
  summary: Python framework for short-term ensemble prediction systems
  license_file: LICENSE
  description: |
    pySTEPS is a community-driven initiative for developing and maintaining an
    easy to use, modular, free and open-source Python framework for short-term
    ensemble prediction systems.
  doc_url: https://pysteps.readthedocs.io/
  dev_url: https://github.com/pySTEPS/pysteps

extra:
  recipe-maintainers:
    - aperezhortal
    - pulkkins
    - dnerini
