{% set name = "pysteps" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pysteps-{{ version }}.tar.gz
  sha256: b81a9a270bc190d8bec27a494d0b24e4d3617b45d1af8ab7329712cf0e7c0ea4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310 or py>312]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - wheel
    - setuptools >=40.8.0
    - cython >=0.29.2
    - numpy >=1.13
    - pip
  run:
    - python
    - jsmin
    - scipy
    - jsonschema
    - numpy
    - matplotlib
    - netCDF4
    - opencv
    - pillow
    - pyproj
test:
  imports:
    - pysteps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pysteps.github.io/
  license: BSD-3-Clause
  license_family: BSD
  summary: Python framework for short-term ensemble prediction systems
  license_file: LICENSE
  description: |
    pySTEPS is a community-driven initiative for developing and maintaining an
    easy to use, modular, free and open-source Python framework for short-term
    ensemble prediction systems.
  doc_url: https://pysteps.readthedocs.io/
  dev_url: https://github.com/pySTEPS/pysteps

extra:
  recipe-maintainers:
    - aperezhortal
    - pulkkins
    - dnerini
